"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { directorBusy } from "@/lib/campaigns/director/types";
import { budgetSchema, budgetUsage, memorySchema } from "@/lib/campaigns/operations";
import type { Campaign } from "@/lib/campaigns/types";
import { campaignRequest, useCampaignStore } from "@/lib/campaigns/client";
import type { SocialAccount } from "@/lib/campaigns/integrations";
import { ExtensionInstall } from "./ExtensionInstall";
import { NativeSelect } from "@/components/ui/native-select";

type Action = (body: unknown) => Promise<void>;
async function connection(path = "", body?: unknown) {
  const response = await fetch(`/api/campaigns/integrations${path}`, body ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : { cache: "no-store" });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || "Connection failed.");
  return result;
}
export function CampaignControls({ campaign, open, onOpenChange, initialTab = "memory" }: { campaign: Campaign; open: boolean; onOpenChange: (value: boolean) => void; initialTab?: string }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [status, setStatus] = useState<{ tiktok: { available: boolean; executable?: string; note: string }; youtube: boolean; postbridge: boolean; workerHeartbeat: number; workerActive: boolean }>();
  const active = directorBusy(campaign) || !!campaign.planning || campaign.runs.some(r => r.status === "running" || r.status === "paused");
  useEffect(() => { if (!open) return; let stopped = false; const refresh = () => connection().then(s => { if (!stopped) setStatus(s); }).catch(() => {}); void refresh(); const timer = setInterval(refresh, 10000); return () => { stopped = true; clearInterval(timer); }; }, [open]);
  const action: Action = async body => {
    setBusy(true); setError(""); setNotice("");
    try { const { campaign: c } = await campaignRequest(`/${campaign.id}`, body); useCampaignStore.getState().setCampaign(c); setNotice("Campaign updated."); }
    catch (e) { setError((e as Error).message); throw e; }
    finally { setBusy(false); }
  };
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent size="wide"><SheetHeader><SheetTitle>Campaign controls</SheetTitle><SheetDescription>Keep your brief, production limits, inspiration, and publishing together.</SheetDescription></SheetHeader><div className="flex-1 overflow-y-auto px-6 pb-8">
    <div className="mb-5 flex flex-wrap items-center gap-2"><Badge variant="outline">{status?.workerActive ? "Background worker active" : "Checking background worker"}</Badge><span className="text-xs text-muted-foreground">Runs while the local app server is running, even with all chats closed.</span></div>
    {notice && <p role="status" className="mb-3 text-sm text-muted-foreground">{notice}</p>}
    {error && <p role="alert" className="mb-4 text-sm text-destructive">{error}</p>}
    <Tabs key={initialTab} defaultValue={initialTab}><TabsList className="w-full"><TabsTrigger value="memory">Memory</TabsTrigger><TabsTrigger value="budget">Budget</TabsTrigger><TabsTrigger value="trends">Discover</TabsTrigger><TabsTrigger value="publishing">Publish</TabsTrigger></TabsList>
      <TabsContent value="memory"><Memory key={campaign.memoryHistory?.length ?? 0} campaign={campaign} action={action} disabled={busy || active} /></TabsContent>
      <TabsContent value="budget"><Budget campaign={campaign} action={action} disabled={busy || active} /></TabsContent>
      <TabsContent value="trends"><p className="mt-4 text-sm text-muted-foreground">Live TikTok discovery runs through a local headless browser with an anonymous visitor session. No account, key, or vendor is involved.</p><p className={`mt-2 text-xs ${status?.tiktok?.available ? "text-muted-foreground" : "text-destructive"}`}>{status?.tiktok?.note ?? "Checking the local browser…"}</p><Discovery campaign={campaign} action={action} disabled={busy} /><details className="mt-6 border-t pt-4"><summary className="cursor-pointer">Instagram Reels · browser extension</summary><div className="mt-4"><ExtensionInstall /></div></details><Connect name="youtube" connected={status?.youtube} refresh={() => connection().then(setStatus)} /></TabsContent>
      <TabsContent value="publishing"><Publishing campaign={campaign} action={action} disabled={busy} /><Connect name="postbridge" connected={status?.postbridge} refresh={() => connection().then(setStatus)} /></TabsContent>
    </Tabs>
  </div></SheetContent></Sheet>;
}
function Memory({ campaign, action, disabled }: { campaign: Campaign; action: Action; disabled: boolean }) {
  const initial = campaign.memory ?? memorySchema.parse({});
  const [products, setProducts] = useState(initial.products);
  return <form className="py-5" onSubmit={e => { e.preventDefault(); const values = Object.fromEntries(new FormData(e.currentTarget)); void action({ action: "memory", memory: { ...values, products } }).catch(() => {}); }}><FieldGroup>
    {([['brand', 'Brand name'], ['brief', 'Campaign brief & objective'], ['audience', 'Audience'], ['voice', 'Voice & tone'], ['constraints', 'Must include / avoid']] as const).map(([key, label]) => <Field key={key}><FieldLabel htmlFor={`memory-${key}`}>{label}</FieldLabel><Textarea id={`memory-${key}`} name={key} defaultValue={initial[key]} disabled={disabled} rows={key === "brief" ? 4 : 2} /></Field>)}
    <Field><FieldLabel>Product references</FieldLabel><p className="text-xs text-muted-foreground">Describe the product and add a page or image reference. Uploaded image references from chat are available below.</p>
    {products.map((p, index) => <FieldGroup key={index} className="rounded-lg border p-4"><Field><FieldLabel htmlFor={`product-${index}`}>Product {index + 1}</FieldLabel><Input id={`product-${index}`} value={p.name} required disabled={disabled} onChange={e => setProducts(products.map((item, i) => i === index ? { ...item, name: e.target.value } : item))} /></Field><Field><FieldLabel htmlFor={`description-${index}`}>Description</FieldLabel><Textarea id={`description-${index}`} value={p.description} disabled={disabled} onChange={e => setProducts(products.map((item, i) => i === index ? { ...item, description: e.target.value } : item))} /></Field><Field><FieldLabel htmlFor={`reference-${index}`}>Reference URL</FieldLabel><Input id={`reference-${index}`} list="uploaded-references" placeholder="https://… or choose an uploaded image" value={p.url} disabled={disabled} onChange={e => setProducts(products.map((item, i) => i === index ? { ...item, url: e.target.value } : item))} /></Field><Button type="button" variant="ghost" disabled={disabled} onClick={() => setProducts(products.filter((_, i) => i !== index))}>Remove product</Button></FieldGroup>)}
    <datalist id="uploaded-references">{campaign.referenceUrls.map(url => <option value={url} key={url} />)}</datalist><Button type="button" variant="outline" disabled={disabled || products.length >= 12} onClick={() => setProducts([...products, { name: "", description: "", url: "" }])}>Add product</Button></Field>
    <Button type="submit" disabled={disabled}>Save campaign memory</Button>
    <details><summary className="cursor-pointer text-sm text-muted-foreground">Brief history · {campaign.memoryHistory?.length ?? 0} versions</summary>{campaign.memoryHistory?.slice().reverse().map(entry => <article key={entry.version} className="mt-3 rounded-lg border p-3"><p className="text-xs text-muted-foreground">v{entry.version} · {new Date(entry.savedAt).toLocaleString()}</p><p className="mt-2 whitespace-pre-wrap text-sm">{entry.memory.brand} — {entry.memory.brief}</p><Button type="button" size="sm" variant="outline" disabled={disabled} onClick={() => void action({ action: "memory", memory: entry.memory }).catch(() => {})}>Restore this version</Button></article>)}</details>
  </FieldGroup></form>;
}
function Budget({ campaign, action, disabled }: { campaign: Campaign; action: Action; disabled: boolean }) {
  const budget = campaign.budget ?? budgetSchema.parse({}), usage = budgetUsage(campaign);
  return <form className="py-5" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const value = (k: string) => f.get(k) === "" ? null : Number(f.get(k)); void action({ action: "budget", budget: { maxGenerations: Number(f.get("maxGenerations")), maxEstimatedUsd: value("maxEstimatedUsd"), imageEstimateUsd: value("imageEstimateUsd"), videoEstimateUsd: value("videoEstimateUsd") } }).catch(() => {}); }}><FieldGroup>
    <p className="text-sm">{usage.generations} generations allocated · ${usage.estimatedUsd.toFixed(2)} estimated{usage.unknown ? " + unpriced submissions" : ""}</p>
    <Field><FieldLabel htmlFor="max-generations">Campaign generation limit</FieldLabel><Input id="max-generations" name="maxGenerations" type="number" min="0" max="10000" required defaultValue={budget.maxGenerations} disabled={disabled} /><p className="text-xs text-muted-foreground">A hard limit across all runs and revisions. Failed or uncertain submissions still count; unstarted cancelled steps are released.</p></Field>
    {([['maxEstimatedUsd', 'Estimated-cost limit (USD)'], ['imageEstimateUsd', 'Kie image estimate per generation (USD)'], ['videoEstimateUsd', 'Video estimate per generation (USD)']] as const).map(([key, label]) => <Field key={key}><FieldLabel htmlFor={key}>{label}</FieldLabel><Input id={key} name={key} type="number" min={key === "maxEstimatedUsd" ? "0" : "0.001"} step="0.001" defaultValue={budget[key] ?? ""} disabled={disabled} placeholder="Not set" /></Field>)}
    <p className="text-xs leading-relaxed text-muted-foreground">Estimates reset when you change generation models. Dollar controls limit planned allocation using your estimates, not the provider’s final bill. Unknown costs block production when a dollar limit is set. Connected-account images reserve $0 in API spend and still count toward the generation limit; subscription usage limits apply separately. API chat costs are unquoted, so dollar-limited campaigns require account-backed chat.</p><Button type="submit" disabled={disabled}>Save budget controls</Button>
  </FieldGroup></form>;
}
function Discovery({ campaign, action, disabled }: { campaign: Campaign; action: Action; disabled: boolean }) {
  return <div className="flex flex-col gap-4 py-5"><p className="text-sm text-muted-foreground">Find recent short videos ranked by views per day, engagement, clip fit and recency. Results are inspiration candidates; motion suitability and reuse rights have not been assessed.</p><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void action({ action: "discover", source: f.get("source"), query: f.get("query"), region: String(f.get("region")).toUpperCase() }).catch(() => {}); }}><FieldGroup><Field><FieldLabel htmlFor="trend-source">Source</FieldLabel><NativeSelect id="trend-source" name="source" defaultValue="tiktok"><option value="tiktok">TikTok · live search (local browser)</option><option value="youtube">YouTube · Data API key</option></NativeSelect></Field><Field><FieldLabel htmlFor="trend-query">Topic or format</FieldLabel><Input id="trend-query" name="query" placeholder="morning routine, outdoor skincare…" minLength={2} maxLength={200} required /></Field><Field><FieldLabel htmlFor="trend-region">Country code (YouTube only)</FieldLabel><Input id="trend-region" name="region" defaultValue="US" pattern="[A-Za-z]{2}" required /></Field><Button type="submit" disabled={disabled}>Discover recent formats</Button></FieldGroup></form>
    <details><summary className="cursor-pointer">Add a TikTok, Reel, or other reference link</summary><form className="mt-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void action({ action: "add-trend", title: f.get("title"), url: f.get("url"), notes: f.get("notes") }).catch(() => {}); }}><FieldGroup><Field><FieldLabel htmlFor="source-title">Reference title</FieldLabel><Input id="source-title" name="title" required /></Field><Field><FieldLabel htmlFor="source-url">Source URL</FieldLabel><Input id="source-url" name="url" type="url" placeholder="https://…" required /></Field><Field><FieldLabel htmlFor="source-notes">What should we adapt?</FieldLabel><Textarea id="source-notes" name="notes" /></Field><Button type="submit" disabled={disabled}>Save reference</Button></FieldGroup></form></details>
    {(campaign.trends ?? []).map(trend => <article key={trend.id} className="flex flex-col gap-2 rounded-xl border p-4"><a href={trend.url} target="_blank" rel="noreferrer" className="font-medium underline">{trend.title}</a><p className="text-xs text-muted-foreground">{trend.manual ? "Added by you · performance not verified" : `${trend.channel} · ${trend.views.toLocaleString()} views · ${trend.viewsPerDay.toLocaleString()} views/day`}</p><p className="text-xs text-muted-foreground">{trend.manual ? trend.notes : `${trend.publishedAt ? `Published ${new Date(trend.publishedAt).toLocaleDateString()} · ` : ""}Checked ${new Date(trend.fetchedAt).toLocaleString()}${trend.notes ? ` · ${trend.notes}` : ""}`}</p><Button variant={trend.selected ? "secondary" : "outline"} disabled={disabled} onClick={() => void action({ action: "select-trend", trendId: trend.id, selected: !trend.selected }).catch(() => {})}>{trend.selected ? "Selected for campaign · Remove" : "Use as campaign inspiration"}</Button></article>)}
  </div>;
}
function Publishing({ campaign, action, disabled }: { campaign: Campaign; action: Action; disabled: boolean }) {
  const [accounts, setAccounts] = useState<SocialAccount[]>([]), [error, setError] = useState("");
  const assets = campaign.assets.filter(a => a.review === "approved" && a.kind !== "text");
  return <div className="flex flex-col gap-4 py-5"><p className="text-sm text-muted-foreground">Create a local draft, review its exact content and destination, then authorize scheduling. Nothing is sent until you schedule it.</p><Button variant="outline" onClick={() => { setError(""); void connection("?accounts=1").then(result => setAccounts(result.accounts)).catch(e => setError(e.message)); }}>Load connected social accounts</Button>{error && <p role="alert" className="text-destructive">{error}</p>}
    <form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void action({ action: "draft-post", draft: { assetIds: [f.get("asset")], accountIds: [Number(f.get("account"))], caption: f.get("caption"), scheduledAt: new Date(String(f.get("scheduled"))).toISOString() } }).catch(() => {}); }}><FieldGroup>
      <Field><FieldLabel htmlFor="post-asset">Approved asset</FieldLabel><NativeSelect id="post-asset" name="asset" required><option value="">Choose an approved image or video</option>{assets.map(a => <option key={a.id} value={a.id}>{a.title} · v{a.version ?? 1}</option>)}</NativeSelect></Field>
      <Field><FieldLabel htmlFor="post-account">Destination</FieldLabel><NativeSelect id="post-account" name="account" required><option value="">Choose a connected account</option>{accounts.map(a => <option key={a.id} value={a.id} disabled={a.needs_reconnect}>{a.platform} · @{a.username}{a.needs_reconnect ? " (reconnect required)" : ""}</option>)}</NativeSelect></Field>
      <Field><FieldLabel htmlFor="post-caption">Caption</FieldLabel><Textarea id="post-caption" name="caption" required maxLength={5000} defaultValue={campaign.assets.filter(a => a.kind === "text").at(-1)?.text ?? ""} /></Field>
      <Field><FieldLabel htmlFor="post-time">Schedule in your local timezone</FieldLabel><Input id="post-time" name="scheduled" type="datetime-local" required /></Field><Button type="submit" disabled={disabled || !assets.length || !accounts.length}>Save local publishing draft</Button>
    </FieldGroup></form>
    {(campaign.posts ?? []).slice().reverse().map(post => <article key={post.id} className="flex flex-col gap-3 rounded-xl border p-4"><div className="flex gap-2"><Badge variant="outline">{post.status}</Badge><span className="text-xs">{new Date(post.scheduledAt).toLocaleString()}</span></div><p className="text-xs text-muted-foreground">{post.assetIds.map(id => campaign.assets.find(a => a.id === id)?.title).join(", ")} → {post.accountIds.map(id => { const a = accounts.find(a => a.id === id); return a ? `${a.platform} @${a.username}` : `Account ${id}`; }).join(", ")}</p><p className="whitespace-pre-wrap text-sm">{post.caption}</p>{post.error && <p className="text-xs text-destructive">{post.error}</p>}{post.status === "draft" && <Button disabled={disabled} onClick={() => void action({ action: "queue-post", postId: post.id }).catch(() => {})}>Approve & schedule this post</Button>}{["draft", "queued", "scheduled", "failed"].includes(post.status) && <Button variant="outline" disabled={disabled} onClick={() => void action({ action: "cancel-post", postId: post.id }).catch(() => {})}>Cancel post</Button>}</article>)}
  </div>;
}
function Connect({ name, connected, refresh }: { name: "youtube" | "postbridge"; connected?: boolean; refresh: () => Promise<void> }) {
  const [error, setError] = useState(""), [busy, setBusy] = useState(false);
  return <details className="mt-6 border-t pt-4"><summary className="cursor-pointer">{name === "youtube" ? "YouTube Data API" : "PostBridge"} · {connected ? "Key configured" : "Connect"}</summary><form className="mt-4" onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; const f = new FormData(form); setBusy(true); setError(""); try { await connection("", { name, key: f.get("key") }); await refresh(); form.reset(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><FieldGroup><Field><FieldLabel htmlFor={`key-${name}`}>API key</FieldLabel><Input id={`key-${name}`} name="key" type="password" autoComplete="off" placeholder="Stored on this local server" required /></Field><Button type="submit" variant="outline" disabled={busy}>Save connection</Button>{error && <p role="alert" className="text-destructive">{error}</p>}</FieldGroup></form></details>;
}
